---
output: github_document
---

# MetaboExploreR: Targeted Mass Spectrometry Processing Pipeline

## Overview

MetaboExploreR provides tools for processing and quality control of targeted 
mass spectrometry vendor files to concentration outputs ready for further analysis.
The package allows for cross platform usage through Docker.

The toolkit consists of three main functions:

**`msConvertR()`**
Processes raw mass spectrometry vendor files into open source mzml files.
Utilising Proteowizards MSconvert. 

**`PeakForgeR()`**
Performs retention time and peak boundary optimisation, peak picking and integration.
    
**`qcCheckR()`**
Performs quality control, batch/signal drift correction, and generates analytical reports.

## Installation
**`Docker Desktop`**
Users are required to install Docker in order to run MetaboExploreR::msConvertR and MetaboExploreR::PeakForgeR.  
Please visit https://www.docker.com/get-started/ for installation process.


Note: Please ensure Docker Application is running in the background when using MetaboExploreR if you are using a Mac or Windows OS.

**`MetaboExploreR`**
Installation is effortless with the below helper function
``` r
source("https://raw.githubusercontent.com/Hszemray/MetaboExplorer/main/install.R")
install_MetaboExplorer()
```
    
## Project Setup 

Create this project folder structure before execution:
    
    User/specified/directory
    └── raw_data #Store vendor files here
    
For example: "C:/User/Desktop/Project1/raw_data"

- Project1 is the name of the project 

- raw_data is a subfolder where I keep the vendor files for the project



## Main User Functions

### 1. msConvertR()

``` r
msConvertR(input_directory, output_directory)
```

####  Workflow:

1.  Converts vendor files → .mzML via ProteoWizard msConvert.
2.  Organises mzml outputs into file structure for each vendor file

### 2. PeakForgeR()

``` r
PeakForgeR(user_name = "User",
           project_directory = "USER/PATH/TO/PROJECT/DIRECTORY",
           mrm_template_list = list("User/path/to/user_mrm_guide_v1.tsv",
                                     "user/path/to/user_mrm_guide_v2.tsv"),
           QC_sample_label = "QC",
           plateID_outputs = NULL
          )
```

#### Workflow:

Process iterates by plate to:

1.  Perform retention time optimisation based on QC samples
2.  Generate PeakForgeR input files
3.  Execute PeakForgeR peak picking and integration
4.  Organise output into plate-specific folders

### 3. qcCheckR()

``` r
qcCheckeR(project_directory,
          mrm_template_list,
          QC_sample_label,
          user_name)
```

#### Workflow:

1.  Batch / signal drift correction using statTarget  
2.  Sample and feature filtering  
3.  Quality metric calculation (RSD, missing values)  
4.  Generation of:
    - Interactive PCA and control chart plots  
    - Quality summary tables  
    - HTML/Excel reports
    
    
## Output Structure

Post-execution directory of msConvertR, PeakForgeR, and qcCheckR:

    User Project Directory
    ├── Archive #Archive of all mzml and wiff files for backup
    ├── ALL
    │   ├── data
    │   │   ├── batch_correction
    │   │   ├── PeakForgeR_reports
    │   │   ├── rda # saved rda from qcCheckR 
    │   └── html_report #Summary of project, PCA, and control charts
    │   └── xlsx_report # Data for further user analysis
    ├── PLATE_NAME # This structure will be created per plate
        ├── data
            ├── mzml #converted mzml files
            ├── rda  #saved rda from PeakForgeR processing
            ├── sciex_raw #original vendor files
            └── PeakForgeR #input and output files of PeakForgeR processing

## Usage Example

### Single project
``` r
project_path <- USER/PATH/TO/PROJECT/DIRECTORY
#Convert vendor files to mzml with msConvert
msConvertR(input_directory = project_path, output_directory = project_path)

# Peak Picking and integration through PeakForgeR
PeakForgeR(project_directory = "project_path", 
         mrm_template_list = list("user_mrm_guide_v1.tsv", 
                                  "user_mrm_guide_v2.csv"
                                  ),
         
                                  )

# Perform QC and calculate concentration data
qcCheckR(project_directory = "project_path", mrm_template_list = mrm_template_list, user_name = "Jane_Doe")
```

### Multiproject pipeline



## Technical Notes

1.  **Dependencies**:
    - Docker Desktop (https://www.docker.com/get-started/) 
2.  **Memory Management**:
    - Process large datasets plate-by-plate
    - Offload processed plate data before processing next plate
3.  **Troubleshooting**:
    - Run R as systems administrator
    - Docker Application is installed and up to date
    - Ensure your R, Rstudio and package versions are all up to date
    - Check vendor files/mzml conversions for corruption 
    - Ensure sufficient disk space
    - Minimum of 8GB RAM required

## Support

For technical assistance, please open an issue at:  
<https://github.com/Hszemray/MetaboExploreR>

